stages:
  - build
  # - deploy
  # - stop_deploy

services:
  - docker:dind

variables:
  IMAGE_NAME: beprimeur

build application:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - if ! command -v ansible &> /dev/null
      then
        apt-get update
        apt-get install ansible
      else
        echo "Ansible est déjà installé sur ce système"
      fi
    # - sudo ansible-playbook build.yml --extra-vars "CI_REGISTRY=$CI_REGISTRY CI_REGISTRY_USER=$CI_REGISTRY_USER CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE CI_COMMIT_SHA=$CI_COMMIT_SHA DEPLOY_TOKEN=$DEPLOY_TOKEN IMAGE_NAME=$IMAGE_NAME"
  only:
    - main
  tags:
    - shell

# deploy application:
#   stage: deploy
#   script:
#     - sudo ansible-playbook deploy.yml
#   only:
#     - main
#   tags:
#     - shell

# stop application deployment:
#   stage: stop_deploy
#   script:
#     - sudo ansible-playbook stop_deploy.yml --extra-vars "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE CI_COMMIT_SHA=$CI_COMMIT_SHA IMAGE_NAME=$IMAGE_NAME"
#   only:
#     - main
#   when: manual
#   tags:
#     - shell

