stages:
  - build
  # - deployment

services:
  - docker:dind

build application:
  state: build
  script:
    - docker-compose build
    - docker login -u $CI_REGISTRY_USER -p $CI_DEPLOY_TOKEN $CI_REGISTRY 
    - docker push $CI_REGISTRY_IMAGE/be-primeur-app:$CI_COMMIT_SHA

  tags:
    - be-primeur-runner