stages:
  - build

services:
  - docker:dind

build application:
  stage: build
  script:
    - docker-compose build
    - docker login -u $CI_REGISTRY_USER -p $DEPLOY_TOKEN $CI_REGISTRY 
    - docker push $CI_REGISTRY_IMAGE/be-primeur-app:$CI_COMMIT_SHA
  tags:
    - shell