stages:
  - build
  - deploy
  - stop_deploy

services:
  - docker:dind

build application:
  stage: build
  script:
    - sudo docker-compose build
    - sudo docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $DEPLOY_TOKEN
    - sudo docker pull $CI_REGISTRY_IMAGE:latest || true
    - sudo docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - sudo docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - main
  tags:
    - shell

deploy application:
  stage: deploy
  script:
    - sudo ansible-playbook deploy.yml
  only:
    - main
  needs:
    - build
  tags:
    - shell

stop application deployment:
  stage: stop_deploy
  script:
    - sudo ansible-playbook stop_deploy.yml
  only:
    - main
  when: manual
  tags:
    - shell

