stages:
  - build
  - deploy
  # - stop_deploy

services:
  - docker:dind

variables:
  IMAGE_NAME: beprimeur

build application:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - sudo docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $DEPLOY_TOKEN
    - sudo docker build -t $IMAGE_NAME .
    - sudo docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - sudo docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - sudo docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - sudo docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - sudo docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - main
  tags:
    - shell

deploy application:
  stage: deploy
  script:
    - sudo ansible-playbook deploy.yml
  only:
    - main
  tags:
    - shell

# stop application deployment:
#   stage: stop_deploy
#   script:
#     - sudo ansible-playbook stop_deploy.yml
#   only:
#     - main
#   when: manual
#   tags:
#     - shell

