- name: Build Be-Primeur Application
  hosts: 127.0.0.1
  become: yes
  gather_facts: false

  tasks:
    - name: Log in to Docker registry
      command: docker login {{ CI_REGISTRY }} -u {{ CI_REGISTRY_USER }} -p {{ DEPLOY_TOKEN }}

    - name: Build and push Docker image
      command: docker build -t {{ IMAGE_NAME }} .

    - name: Tag Docker Image
      command: docker tag {{ IMAGE_NAME }} {{ CI_REGISTRY_IMAGE }}:{{ CI_COMMIT_SHA }}

    - name: Push Docker Image
      command: docker push {{ CI_REGISTRY_IMAGE }}:{{ CI_COMMIT_SHA }}

    - name: Pull Docker image
      command: docker pull {{ CI_REGISTRY_IMAGE }}:{{ CI_COMMIT_SHA }} || true

    - name: Build Docker image with cache
      command: docker build --cache-from {{ CI_REGISTRY_IMAGE }}:{{ CI_COMMIT_SHA }} --tag {{ CI_REGISTRY_IMAGE }}:{{ CI_COMMIT_SHA }} .

    - name: Push Docker image
      command: docker push {{ CI_REGISTRY_IMAGE }}:{{ CI_COMMIT_SHA }}