- name: Deploy Be-Primeur Application
  become: yes
  hosts: 127.0.0.1

  tasks:
  - name: Start docker
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install mysqli extension
    docker_container:
      name: www
      image: php:7.4-apache
      state: started
      command: docker-php-ext-install mysqli pdo pdo_mysql

  - name: Build Application
    docker_compose:
      project_src: ./
      build: yes
      pull: yes

  - name: Up containers with docker_compose
    docker_compose:
      project_src: ./
      state: present
