- name: Deploy Be-Primeur Application
  become: yes
  hosts: localhost

  tasks:
  - name: Start docker
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Login to registry Gitlab
    docker_login:
      registry_url: "{{ lookup('env', 'CI_REGISTRY') }}"
      username: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
      password: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"
    register: login_result

  # - name: Log CI_REGISTRY variable
  #   debug:
  #     var: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}"

  - name: Extract image from GitLab registry
    command: docker pull "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}:{{ lookup('env','CI_COMMIT_SHA') }}"

    # when: login_result.login_result.Status = "Login Succeeded"



  # - name: Build Application Web
  #   docker_image:
  #     name: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}:latest"
  #     pull: yes
  #     path: ./
  #     tag: "{{ lookup('env', 'CI_COMMIT_SHA') }}"
  #   when: login_result.logged_in

  # - name: Up containers with docker_compose
  #   docker_compose:
  #     project_src: ./
  #     state: present