- name: Deploy Be-Primeur Application
  become: yes
  hosts: localhost

  tasks:
  - name: Start docker
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Pull Docker image from GitLab registry
    docker_login:
      registry_url: "{{ lookup('env', 'CI_REGISTRY') }}"
      username: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
      password: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"
    register: login_result

  # - name: Check if Docker image already exists
  #   docker_image:
  #     name: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}:{{ lookup('env', 'CI_COMMIT_SHA') }}"
  #     source: pull
  #   register: docker_pull
  #   until: docker_pull is succeeded
  #   retries: 5

  - name: Check if Docker image already exists
    docker_image:
      name: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}:{{ lookup('env', 'CI_COMMIT_SHA') }}"
      source: inspect
      tag: "{{ lookup('env', 'CI_COMMIT_SHA') }}"
    register: docker_inspect

  - name: Build Application if necessary
    docker_image:
      name: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}:{{ lookup('env', 'CI_COMMIT_SHA') }}"
      build:
        path: ./
      source: build
      tag: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}:{{ lookup('env', 'CI_COMMIT_SHA') }}"
      force_build: yes
    when: login_result.changed or docker_pull.changed

  # - name: Build Application if necessary
  #   docker_image:
  #     name: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}:{{ lookup('env', 'CI_COMMIT_SHA') }}"
  #     build:
  #       path: ./
  #     source: build
  #     tag: latest
  #     force_build: yes
  #   when: docker_inspect|failed or login_result.changed

  - name: Up containers with docker_compose
    docker_compose:
      project_src: ./
      state: present
