- name: Deploy Be-Primeur Application
  become: yes
  hosts: 127.0.0.1

  tasks:
  - name: Start docker
    systemd:
      name: docker
      state: started
      enabled: yes

  # - name: Check if Docker image already exists
  #   shell: docker inspect beprimeur:latest
  #   register: docker_inspect
  #   ignore_errors: true

  - name: Build Application
    docker_compose:
      project_src: ./
      build: yes
      pull: yes

  - name: Up containers with docker_compose
    docker_compose:
      project_src: ./
      up: yes