version: '3'
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" 
    ports:
      - 8082:80    
    environment:
      - DB_HOST=db
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_DATABASE=be_primeur
    restart: always
    depends_on:
      - db
    command: >
      bash -c "
        docker-php-ext-install mysqli
        && apache2-foreground
      "
      
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=be_primeur
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - host_cache_size=0
    restart: always
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    restart: always
    depends_on:
      - db