version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=be_primeur
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - host_cache_size=0
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" 
    ports:
      - 8082:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306


