- name: Be Primeur Application Web
  hosts: all
  become: true
  roles:
    - { role: 'docker', tags: 'package' }
    - { role: 'build', tags: 'build' }
    - { role: 'deployment', tags: 'deployment' }
    - { role: 'stop_deployment', tags: 'stop' }

# ansible-playbook playbook.yml --tags "package"
