- name: Stop all services
  command: docker stop $(docker ps -a -q)

- name: Remove Docker images
  docker_image:
    name: "{{ item }}"
    state: absent
    force: yes
  with_items:
    - "{{ CI_REGISTRY_IMAGE }}:{{ CI_COMMIT_SHA }}"
    - "{{ IMAGE_NAME }}"
