- name: Stop all services
  docker_compose:
    project_src: ./
    stopped: true
    state: absent

- name: Remove Docker images
  docker_image:
    name: "{{ item }}"
    state: absent
    force: yes
  with_items:
    - "{{ CI_REGISTRY_IMAGE }}:{{ CI_COMMIT_SHA }}"
    - "{{ IMAGE_NAME }}"
