- name: Stop all services
  command: docker-compose -f /home/vagrant/Be-Primeur/docker-compose.yml down

- name: Remove Docker images
  command: "docker rmi {{ item }} -f"
  with_items:
    - "{{ CI_REGISTRY_IMAGE }}:{{ CI_COMMIT_SHA }}"
    - "{{ IMAGE_NAME }}"
