- name: Recueil des faits des packages
  ansible.builtin.package_facts:

- name: Installation des dépendances
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  when: item not in ansible_facts.packages

- name: Ajout de la clé GPG officielle de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    validate_certs: yes  

- name: Configuration du référentiel
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Instalaltion de docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: item not in ansible_facts.packages

- name: Check si docker-compose est installé
  stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose_installed

- name: Téléchargement et installation de docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: not docker_compose_installed.stat.exists

- name: Démarrage du service docker
  become: true
  systemd:
    name: docker
    state: started
- name: Vérifie que docker est actif
  service:
    name: docker
    state: started
    enabled: yes