- name: Package facts
  ansible.builtin.package_facts:

- name: Installing dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  when: item not in ansible_facts.packages

- name: Added official Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    validate_certs: yes  

- name: Repository configuration
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Docker installation
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: item not in ansible_facts.packages

- name: Check if docker-compose is installed
  stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose_installed

- name: Download and install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: not docker_compose_installed.stat.exists

- name: Copier un répertoire local vers la machine distante
  copy:
    src: ./
    dest: ./

- name: Starting docker service
  become: true
  systemd:
    name: docker
    state: started

- name: Check that docker is active
  service:
    name: docker
    state: started
    enabled: yes